packages:
  - .

minimumReleaseAge: 2880 # 48 hrs
minimumReleaseAgeExclude:
  - '@next/*'
  - eslint-config-next
  - next
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/engines'
  - '@swc/core'
  - better-sqlite3
  - cbor-extract
  - esbuild
  - msw
  - prisma
  - sharp
